r1:
	g++ -lpthread cfindprime_v1.cpp -o cfindprime_v1
r2:
	for i in {1..100}; do ./cfindprime_v1;  done

r3:
	g++ -lpthread cfindprime_v2.cpp -o cfindprime_v2
r4:
	for i in {1..100}; do ./cfindprime_v2;  done

r5:
	g++ -lpthread cfindprime_v3.cpp -o cfindprime_v3
r6:
	for i in {1..100}; do ./cfindprime_v3;  done
