csudokuchecker:
	g++ -o csudokuchecker -lpthread csudokuchecker.cpp
run:
	./csudokuchecker
csudokucheckerg:
	g++ -g -o csudokucheckerg -lpthread csudokuchecker.cpp
clean:
	find . -maxdepth 1 -type f -executable -exec rm {} +
