compile_sequential:
	gcc -o sequentialprime sequentialprime.c -lm
run_sequential:
	./sequentialprime

compile_segsequential:
	gcc -o sprime2 sprime2.c -lm
run_segsequential:
	./sprime2

compile_multithreading:
	gcc -o pprime3 pprime3.c -lm -lpthread 
run_multithreading:
	./pprime3

compile_multithreadingconcurrent:
	gcc -o pprime4 pprime4.c -lm -lpthread 
run_multithreadingconcurrent:
	./pprime4

compile_multithreadingdynamic:
	gcc -o pprime5 pprime5.c -lm -lpthread 
run_multithreadingdynamic:
	./pprime5
